Programmiermethoden/Deploy-to-Grading

doc/related_work/book/bott2017.md
doc/related_work/book/readme.md
doc/related_work/paper/dietz2018.md
doc/related_work/paper/readme.md
doc/related_work/readme.md

[D2G] Ergänzungen zum Related Work

---

doc/related_work/autograder/codefreak.md

die CodeFreak-Leute haben auch nen Artikel in der "Neuen Hochschule" gehabt ...

Related work: add article on CodeFreak

---

doc/related_work/paper/dietz2019.md
doc/related_work/paper/readme.md

[Documentation] Add related work Dietz 2019

---

doc/related_work/book/bott2017.md

[Documentation] Fix bott2017 url

---

scripts/checkout_due_date.sh

Closes #42
Implementierung für das Auschecken des letzten Commits vor dem Abgabedatum.

[D2G] checkout_due_date-Skript hinzugefügt

---

scripts/checkout_due_date.sh
scripts/deploy_to_grading.py
scripts/load_yaml.py
scripts/metrics/compile_eval.py

Korrigiert ein paar Fehler, die ich beim Erstellen der Codedokumentation übersehen habe.

[D2G] Typos gefixt

---

scripts/create_artifact.sh
scripts/deploy_to_grading.py

Closes #75.
Skript zum Sammeln der Ergebnisse und Erstellen eines `zip`-Archivs hinzugefügt.  Getestet in der vollständigen Pipeline mit meinem Hello-World Beispiel.

[D2G] create_artifact.sh hinzugefügt

---

scripts/deploy_to_grading.py

Formuliert ein TODO um, das bereits implementiert wurde.

[D2G] Fix: Fertiges TODO entfernt

---

scripts/deploy_to_grading.py
scripts/get_students_involved.py
scripts/print_results_student.py

Closes #16.
Fügt eine Zusammenfassung der Ergebnisse für Studierende gemäß Dokumentation hinzu (und löscht noch ein unnötiges Print).

[D2G] Konsolenausgabe der Ergebnisse für Studierende hinzugefügt

---

scripts/metrics/metric_utils.py

Fixed kleinen Fehler, der durchgerutscht ist.

[D2G] Fixed unbekannte USAGE Variable

---

scripts/metrics/codeformat_eval.py
scripts/metrics/compile_eval.py
scripts/metrics/javadoc_eval.py
scripts/metrics/junit_eval.py
scripts/metrics/metric_utils.py

Ergänzung zum bereits geschlossenen #79.

[D2G] get_taskname() ausgelagert nach metric_utils.py

---

CITATION.cff

@AKirsch1 Bitte ein kurzes Review+Freigabe. Dieser PR fügt ein sogenanntes CFF hinzu, um Nachnutzenden eine korrekte Zitation zu ermöglichen.

[Org] add how to cite

---

doc/related_work/autograder/cofee.md
doc/related_work/autograder/coursemarker.md
doc/related_work/autograder/readme.md
doc/related_work/autograder/webcat.md
doc/related_work/paper/readme.md
doc/related_work/paper/strickroth2022.md

Basierend auf den Erkenntnissen vom ABP-Workshop habe ich in der Related Work-Dokumentation ein paar zusätzliche Beschreibungen hinzugefügt.

[Documentation] Fügt weiteres Related Work hinzu

---

requirements-teacher.txt
scripts/deploy_to_grading_teacher.py
scripts/print_results_student.py
scripts/result_utils.py

Closes #44.
Fügt ein Skript für Lehrende hinzu, um die Studierenabgaben final zu bewerten. Da ILIAS eine Excel-Datei ausspuckt, habe ich mich dazu entschieden, auch als Ausgabe eine Exceldatei zu verwenden.

[D2G] Fügt Aufgabenblatt-Skript für Lehrende hinzu

---

scripts/metrics/junit_eval.py
scripts/metrics/metric_utils.py

[D2G] Private generate_final_results-Funktion zu Public geändert

---

scripts/checkout_due_date.sh
scripts/deploy_to_grading.py
scripts/revert_checkout.sh

[D2G] Fix: checkout_due_date.sh setzt HEAD nicht zurück

---

doc/metrics/create_custom_metric.md
doc/metrics/readme.md

[D2G] Fügt eine Dokumentation zur Erstellung neuer Metriken hinzu

---

doc/metrics/junit.md
scripts/metrics/junit_eval.py

[D2G] JUnit Metrik: Einstellung default_points ist jetzt optional

---

doc/readme.md
doc/teacher_scripts.md

[Documentation] Fügt Dokumentation für die Skripte für Lehrende hinzu

---

doc/create_tasks_repository.md
doc/readme.md

[Documentation] Fügt Dokumentation zum Thema "Erstellen eines Aufgabenrepositorys" hinzu

---

doc/teacher_scripts.md
scripts/deploy_to_grading_teacher.py
scripts/metrics/jplag.sh
scripts/metrics/jplag_eval.py

[D2G] Fügt Plag Metrik für das Lehrende-Skript hinzu 

---

README.md

[Documentation] Bibtex-Eintrag in Readme hinzugefügt

---

scripts/override_repo.py

Entfernt Todo Notiz aus dem Code, welche im geschlossenen Issue #67 referenziert wird.

[D2G] Entfernt Todo in override_repo.py

---

scripts/deploy_to_grading.py
scripts/override_repo.py

[D2G] Änderungen der Konfiguration durch Studierende nicht mehr möglich

---

scripts/metrics/junit_eval.py

[D2G] JUnit Metrik: Evaluation schlug fehl, wenn keine einzige Testdatei kompiliert werden konnte.

---

README.md

In README.md.
Und ein kleiner Bibtex Fix, für den sich kein eigner PR lohnt.

[Documentation] Link zur Demo hinzugefügt
